# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from configparser import ConfigParser

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QPalette, QBrush
from PyQt5.QtWidgets import QLineEdit, QApplication

cfg = ConfigParser()
cfg.read(os.path.join(os.path.join(os.path.expanduser('~'), 'dist'), "setting.ini"))
setting_data = dict(cfg.items("dev"))


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        self.LoginWindow = LoginWindow
        LoginWindow.setObjectName("LoginWindow")
        height_mul = QApplication.desktop().screenGeometry().height()/1080
        width_mul = QApplication.desktop().screenGeometry().width()/1960
        LoginWindow.resize(1600 * height_mul, 900 * width_mul)
        # LoginWindow.resize(1600, 900)
        background_img = QPixmap(os.path.join(os.path.expanduser('~'), setting_data['login background']))
        background_img = background_img.scaled(LoginWindow.width(), LoginWindow.height())
        palette = QPalette()
        palette.setBrush(QPalette.Background, QBrush(background_img))
        LoginWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.label1.setGeometry(QtCore.QRect(940 * height_mul, 313 * width_mul, 27 * height_mul, 26 * width_mul))
        self.label1.setPixmap(QPixmap(os.path.join(os.path.expanduser('~'), setting_data['user img'])))
        self.student_id = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_id.sizePolicy().hasHeightForWidth())
        self.student_id.setSizePolicy(sizePolicy)
        self.student_id.setObjectName("student_id")
        self.student_id.setGeometry(QtCore.QRect(980 * height_mul, 300 * width_mul, 200 * height_mul, 50 * width_mul))
        self.student_id.setPlaceholderText('     请输入用户名')
        self.student_id.setStyleSheet("background:transparent;border-width:0;border-style:outset")
        self.label1_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_2.sizePolicy().hasHeightForWidth())
        self.label1_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label1_2.setFont(font)
        self.label1_2.setObjectName("label1_2")
        self.label1_2.setGeometry(QtCore.QRect(937 * height_mul, 413 * width_mul, 27 * height_mul, 26 * width_mul))
        self.label1_2.setPixmap(QPixmap(os.path.join(os.path.expanduser('~'), setting_data['password img'])))
        self.student_pwd = QtWidgets.QLineEdit(self.centralwidget)
        self.student_pwd.setEchoMode(QLineEdit.Password)
        self.student_pwd.setPlaceholderText('     请输入登录密码')
        # self.student_pwd.setEchoMode(QLineEdit::Password)
        self.student_pwd.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_pwd.sizePolicy().hasHeightForWidth())
        self.student_pwd.setSizePolicy(sizePolicy)
        self.student_pwd.setObjectName("student_pwd")
        self.student_pwd.setStyleSheet("background:transparent;border-width:0;border-style:outset")
        self.student_pwd.setGeometry(QtCore.QRect(980 * height_mul, 400 * width_mul, 200 * height_mul, 50 * width_mul))
        self.login = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.login.setGeometry(QtCore.QRect(968 * height_mul, 490 * width_mul, 224 * height_mul, 36 * width_mul))
        self.login.setStyleSheet("QPushButton{color:white}"
                                 "QPushButton{background-color:rgb(42,93,198)}")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "考试登陆"))
        # self.label1.setText(_translate("LoginWindow", "账户"))
        # self.label1_2.setText(_translate("LoginWindow", "密码"))
        self.login.setText(_translate("LoginWindow", "登录"))
