# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
from configparser import ConfigParser

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication

cfg = ConfigParser()
cfg.read(os.path.join(os.path.join(os.path.expanduser('~'), 'dist'), "setting.ini"))
setting_data = dict(cfg.items("dev"))


class Ui_ExamWindow(object):
    def setupUi(self, ExamWindow):
        ExamWindow.setObjectName("ExamWindow")
        height_mul = QApplication.desktop().screenGeometry().height() / 1080
        width_mul = QApplication.desktop().screenGeometry().width() / 1960

        ExamWindow.resize(1600 * height_mul, 900 * width_mul)
        ExamWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(ExamWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.new_label1 = QtWidgets.QLabel(self.centralwidget)
        self.new_label1.setObjectName("new_label1")
        self.vtd_start = QtWidgets.QPushButton(self.centralwidget)
        self.vtd_start.setObjectName("vtd_start")
        self.vtd_start.setStyleSheet("QPushButton{color:white}"
                                     "QPushButton{background-color:rgb(42,93,198)}"
                                     "QPushButton{border:1px}"
                                     "QPushButton{border-radius:10px}"
                                     "QPushButton{padding:1px 1px}")
        self.vtd_quit = QtWidgets.QPushButton(self.centralwidget)
        self.vtd_quit.setObjectName("vtd_quit")
        self.vtd_quit.setStyleSheet("QPushButton{color:white}"
                                    "QPushButton{background-color:rgb(42,93,198)}"
                                    "QPushButton{border:1px}"
                                    "QPushButton{border-radius:10px}"
                                    "QPushButton{padding:1px 1px}")
        self.new_label2 = QtWidgets.QLabel(self.centralwidget)
        self.new_label2.setObjectName("new_label2")
        self.configurations = QtWidgets.QPushButton(self.centralwidget)
        self.configurations.setObjectName("configurations")
        self.configurations.setStyleSheet("QPushButton{color:white}"
                                          "QPushButton{background-color:rgb(42,93,198)}"
                                          "QPushButton{border:1px}"
                                          "QPushButton{border-radius:10px}"
                                          "QPushButton{padding:1px 1px}")
        self.new_label3 = QtWidgets.QLabel(self.centralwidget)
        self.new_label3.setObjectName("new_label3")
        self.algo_start = QtWidgets.QPushButton(self.centralwidget)
        self.algo_start.setObjectName("algo_start")
        self.algo_start.setStyleSheet("QPushButton{color:white}"
                                      "QPushButton{background-color:rgb(42,93,198)}"
                                      "QPushButton{border:1px}"
                                      "QPushButton{border-radius:10px}"
                                      "QPushButton{padding:1px 1px}")
        self.algo_quit = QtWidgets.QPushButton(self.centralwidget)
        self.algo_quit.setObjectName("algo_quit")
        self.algo_quit.setStyleSheet("QPushButton{color:white}"
                                     "QPushButton{background-color:rgb(42,93,198)}"
                                     "QPushButton{border:1px}"
                                     "QPushButton{border-radius:10px}"
                                     "QPushButton{padding:1px 1px}")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(1500 * height_mul, 11 * width_mul, 80 * height_mul, 40 * width_mul))
        self.exit.setStyleSheet("QPushButton{color:white}"
                                "QPushButton{background-color:rgb(42,93,198)}"
                                "QPushButton{border:1px}"
                                "QPushButton{border-radius:10px}"
                                "QPushButton{padding:1px 1px}")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit.sizePolicy().hasHeightForWidth())
        self.exit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.student_id = QtWidgets.QLabel(self.centralwidget)
        self.student_id.setGeometry(QtCore.QRect(1400 * height_mul, 10 * width_mul, 130 * height_mul, 50 * width_mul))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_id.sizePolicy().hasHeightForWidth())
        self.student_id.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.student_id.setFont(font)
        self.student_id.setObjectName("student_id")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(1350 * height_mul, 10 * width_mul, 50 * height_mul, 50 * width_mul))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(650 * height_mul, 800 * width_mul, 200 * height_mul, 50 * width_mul))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit_button.sizePolicy().hasHeightForWidth())
        self.submit_button.setSizePolicy(sizePolicy)
        self.submit_button.setObjectName("submit_button")
        self.submit_button.setStyleSheet("QPushButton{color:white}"
                                         "QPushButton{background-color:rgb(42,93,198)}"
                                         "QPushButton{border:1px}"
                                         "QPushButton{border-radius:10px}"
                                         "QPushButton{padding:1px 1px}")
        self.exam_desc = QtWidgets.QLabel(self.centralwidget)
        self.exam_desc.setGeometry(QtCore.QRect(50 * height_mul, 130 * width_mul, 1450 * height_mul, 600 * width_mul))
        self.exam_desc.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.exam_desc.setText("")
        self.exam_desc.setObjectName("exam_desc")


        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(15 * height_mul, 830 * width_mul, 200 * height_mul, 100 * width_mul))
        self.version.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.version.setFont(font)
        self.version.setText(f"当前版本：V{setting_data['version']}")
        self.version.setObjectName("version")

        ExamWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ExamWindow)
        QtCore.QMetaObject.connectSlotsByName(ExamWindow)

    def retranslateUi(self, ExamWindow):
        _translate = QtCore.QCoreApplication.translate
        ExamWindow.setWindowTitle(_translate("ExamWindow", "智能网联汽车虚拟仿真测试平台"))
        self.exit.setText(_translate("ExamWindow", "退出"))
        self.student_id.setText(_translate("ExamWindow", "0"))
        self.label1.setText(_translate("ExamWindow", "考生:"))
        self.submit_button.setText(_translate("ExamWindow", "开始考试"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ExamWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
